[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D ZENOH_COMPILER_GCC
    -D ZENOH_ARDUINO_ESP32

lib_extra_dirs = ../../shared_libraries/mcu

lib_ignore = 
    FreeRTOS

lib_deps = 
    zenoh_ros
    https://github.com/eclipse-zenoh/zenoh-pico.git
    bblanchon/ArduinoJson@^7.1.0
    fastled/FastLED@~3.10.3
